// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGETIC.Infrastructure.Persistence;

#nullable disable

namespace SIGETIC.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SigeticDbContext))]
    [Migration("20260616010025_RenderInitialSchema")]
    partial class RenderInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGETIC.Domain.Entities.BajaEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisposicionFinal")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("disposicion_final");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<string>("EstadoFisico")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("estado_fisico");

                    b.Property<DateOnly>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("MotivoBaja")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("motivo_baja");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("ResponsableBaja")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsable_baja");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("FechaBaja");

                    b.ToTable("bajas_equipo", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Consumible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("color");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("MarcaCompatible")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("marca_compatible");

                    b.Property<string>("ModelosCompatibles")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("modelos_compatibles");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referencia");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("TipoConsumible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_consumible");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.ToTable("consumibles", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Dependencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Correo")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre");

                    b.Property<string>("Responsable")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsable");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("dependencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Activa = true,
                            Codigo = "PLA",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Secretaría de Planeación",
                            Responsable = "Secretaría de Planeación"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Activa = true,
                            Codigo = "SIS",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Sistemas",
                            Responsable = "Profesional TIC"
                        });
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("almacenamiento");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_interno");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("dependencia");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("DireccionMac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion_mac");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("FuncionarioAsignado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("funcionario_asignado");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marca");

                    b.Property<string>("MemoriaRam")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("memoria_ram");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Procesador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("procesador");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("serial");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sistema_operativo");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_equipo");

                    b.Property<string>("UbicacionFisica")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("ubicacion_fisica");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cargo");

                    b.Property<string>("Correo")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("correo");

                    b.Property<Guid>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("documento");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.HistorialConsumibleImpresora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("color");

                    b.Property<int?>("ContadorPaginas")
                        .HasColumnType("integer")
                        .HasColumnName("contador_paginas");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly>("FechaMovimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_movimiento");

                    b.Property<Guid>("ImpresoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("impresora_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referencia");

                    b.Property<string>("ResponsableEntrega")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsable_entrega");

                    b.Property<string>("TipoConsumible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_consumible");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("Id");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("historial_consumibles_impresora", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Impresora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<Guid>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("DireccionMac")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("direccion_mac");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid?>("FuncionarioAsignadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_asignado_id");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serial");

                    b.Property<string>("TecnologiaImpresion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tecnologia_impresion");

                    b.Property<string>("TipoImpresora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_impresora");

                    b.Property<string>("UbicacionFisica")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("ubicacion_fisica");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("DependenciaId");

                    b.HasIndex("FuncionarioAsignadoId");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("impresoras", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MantenimientoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActividadesRealizadas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("actividades_realizadas");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("diagnostico");

                    b.Property<string>("DocumentoRecibe")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("documento_recibe");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<string>("EstadoResultante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("estado_resultante");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaFirmaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_firma_utc");

                    b.Property<DateOnly>("FechaMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_mantenimiento");

                    b.Property<string>("FirmaRecibe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firma_recibe");

                    b.Property<string>("FirmaTecnico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firma_tecnico");

                    b.Property<string>("NombreRecibe")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre_recibe");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<DateOnly?>("ProximaRevision")
                        .HasColumnType("date")
                        .HasColumnName("proxima_revision");

                    b.Property<string>("RepuestosUtilizados")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("repuestos_utilizados");

                    b.Property<string>("TecnicoResponsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tecnico_responsable");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_mantenimiento");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("FechaMantenimiento");

                    b.ToTable("mantenimientos_equipo", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MantenimientoImpresora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActividadesRealizadas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("actividades_realizadas");

                    b.Property<int?>("ContadorPaginas")
                        .HasColumnType("integer")
                        .HasColumnName("contador_paginas");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("diagnostico");

                    b.Property<string>("DocumentoRecibe")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("documento_recibe");

                    b.Property<string>("EstadoResultante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado_resultante");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaFirmaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_firma_utc");

                    b.Property<DateOnly>("FechaMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_mantenimiento");

                    b.Property<string>("FirmaRecibe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firma_recibe");

                    b.Property<string>("FirmaTecnico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firma_tecnico");

                    b.Property<Guid>("ImpresoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("impresora_id");

                    b.Property<string>("NombreRecibe")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre_recibe");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<DateOnly?>("ProximaRevision")
                        .HasColumnType("date")
                        .HasColumnName("proxima_revision");

                    b.Property<string>("RepuestosUtilizados")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("repuestos_utilizados");

                    b.Property<string>("TecnicoResponsable")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("tecnico_responsable");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_mantenimiento");

                    b.HasKey("Id");

                    b.HasIndex("FechaMantenimiento");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("mantenimientos_impresora", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MovimientoConsumible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("ConsumibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumible_id");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("costo_total");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<Guid?>("DependenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("Destino")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("destino");

                    b.Property<string>("DocumentoSoporte")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("documento_soporte");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly>("FechaMovimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_movimiento");

                    b.Property<Guid?>("ImpresoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("impresora_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsable");

                    b.Property<int>("StockResultante")
                        .HasColumnType("integer")
                        .HasColumnName("stock_resultante");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("Id");

                    b.HasIndex("ConsumibleId");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("movimientos_consumibles", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("accion");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modulo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Descripcion = "Acceso total al sistema SIGETIC.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            Descripcion = "Gestión técnica de inventario, mantenimientos, impresoras, consumibles y mesa de ayuda.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador TIC"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            Descripcion = "Apoyo operativo en mantenimientos, tickets, impresoras y consumibles.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Auxiliar de Sistemas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            Descripcion = "Usuario interno para creación y consulta de solicitudes.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Funcionario"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            Descripcion = "Acceso de solo consulta a reportes y trazabilidad.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Consulta / Control Interno"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Activo = true,
                            Descripcion = "Apoyo administrativo de la Secretaría Administrativa Financiera para consumibles, reportes y trazabilidad.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Auxiliar Administrativo SAF"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Activo = true,
                            Descripcion = "Acceso directivo de consulta, reportes, analítica, tickets y actualización de consumibles.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Secretario Administrativo Financiero"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Activo = true,
                            Descripcion = "Acceso para visualizar dashboard y crear solicitudes en mesa de ayuda.",
                            EsSistema = true,
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Secretario de Despacho"
                        });
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.TicketMesaAyuda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CalificacionAmabilidad")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_amabilidad");

                    b.Property<int?>("CalificacionAtencion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_atencion");

                    b.Property<int?>("CalificacionSolucion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_solucion");

                    b.Property<int?>("CalificacionTiempo")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_tiempo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("ComentarioSatisfaccion")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("comentario_satisfaccion");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("dependencia");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("EquipoCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("equipo_codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateOnly?>("FechaCompromiso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_compromiso");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaEncuestaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_encuesta_utc");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("ImpresoraCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("impresora_codigo");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("prioridad");

                    b.Property<string>("ResponsableAsignado")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsable_asignado");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("solicitante");

                    b.Property<string>("Solucion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("solucion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaSolicitud");

                    b.HasIndex("Prioridad");

                    b.ToTable("tickets_mesa_ayuda", (string)null);
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UltimoAccesoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_utc");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Activo = true,
                            Correo = "admin@sigetic.local",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador SIGETIC",
                            PasswordHash = "PBKDF2$100000$U0lHRVRJQy1TRUVELTEyMw==$oVgabe+uhoKIpI5ySW5DiJV57uFA33l7lzdffPwU30A=",
                            RolId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999901"),
                            Activo = true,
                            Correo = "secretario.administrativo@sigetic.local",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Secretario Administrativo Financiero",
                            PasswordHash = "PBKDF2$100000$U0lHRVRJQy1TRUVELTEyMw==$CcD5E2RqWu4gVWIrvU4M+JPC/m9tMGOmLLZLcf8aHRc=",
                            RolId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999902"),
                            Activo = true,
                            Correo = "administrador.tic@sigetic.local",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador TIC",
                            PasswordHash = "PBKDF2$100000$U0lHRVRJQy1TRUVELTEyMw==$CcD5E2RqWu4gVWIrvU4M+JPC/m9tMGOmLLZLcf8aHRc=",
                            RolId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999903"),
                            Activo = true,
                            Correo = "auxiliar.administrativo@sigetic.local",
                            FechaCreacionUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Auxiliar Administrativo - Secretaría Administrativa Financiera",
                            PasswordHash = "PBKDF2$100000$U0lHRVRJQy1TRUVELTEyMw==$CcD5E2RqWu4gVWIrvU4M+JPC/m9tMGOmLLZLcf8aHRc=",
                            RolId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.BajaEquipo", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.HistorialConsumibleImpresora", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Impresora", "Impresora")
                        .WithMany()
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Impresora", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGETIC.Domain.Entities.Funcionario", "FuncionarioAsignado")
                        .WithMany()
                        .HasForeignKey("FuncionarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependencia");

                    b.Navigation("FuncionarioAsignado");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MantenimientoEquipo", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MantenimientoImpresora", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Impresora", "Impresora")
                        .WithMany()
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.MovimientoConsumible", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Consumible", "Consumible")
                        .WithMany()
                        .HasForeignKey("ConsumibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGETIC.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGETIC.Domain.Entities.Impresora", "Impresora")
                        .WithMany()
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consumible");

                    b.Navigation("Dependencia");

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGETIC.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SIGETIC.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SIGETIC.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
